server:
  port: 1234

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///store
    username: root
    password: 12581cvb


mybatis:
  mapper-locations: classpath:mapper/*.xml


user:
  address:
    max-count: 20

# server.servlet.context-path=/store
# spring.servlet.multipart.maxFileSize=10MB
# spring.servlet.multipart.maxRequestSize=10MB
